### ISSUE TITLE
异常SocketException perimission denied:connect

### ISSUE THREAD

**Issue by vseal001** [Stars-One/LanzouDownloader#1]
java.net.SocketException: Permission denied: connect
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:368)
	at com.gargoylesoftware.htmlunit.httpclient.HtmlUnitSSLConnectionSocketFactory.connectSocket(HtmlUnitSSLConnectionSocketFactory.java:184)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:374)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
	at com.gargoylesoftware.htmlunit.HttpWebConnection.getResponse(HttpWebConnection.java:189)
	at com.gargoylesoftware.htmlunit.WebClient.loadWebResponseFromWebConnection(WebClient.java:1407)
	at com.gargoylesoftware.htmlunit.WebClient.loadWebResponse(WebClient.java:1326)
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:396)
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:317)
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:469)
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:450)
	at com.wan.view.MainController.download(MainView.kt:106)
	at com.wan.view.MainController.download$default(MainView.kt:95)
	at com.wan.view.MainView$root$1$2$1$1$3$1$1.invoke(MainView.kt:57)
	at com.wan.view.MainView$root$1$2$1$1$3$1$1.invoke(MainView.kt:19)
	at tornadofx.FXTask.call(Async.kt:463)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by stars-one** [comment]
你的ip可能被蓝奏云列入黑名单了，你可以随便访问一个蓝奏云连接看看，如果访问不了，就是被列入黑名单了，你那个设置的自动翻页数过大

解决方法就是改IP地址，重新连接宽带，IP地址就会发生改变

**Comment by vseal001** [comment]
谢谢大佬回复，
但是默认页数5没变，还有就是我浏览器能进，可能API解析有问题了吧。
使用环境：win10 powershell admin

**Comment by stars-one** [comment]
蓝奏云的地址是什么？我测试下

**Comment by stars-one** [comment]
v1.8 新版本已修复分页
